FUNCTION ZFM_BM_RPC_INPUT_MANUAL_DATA.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_RPC_F) TYPE  ZVI_BM_RPC_F
*"----------------------------------------------------------------------
  DATA:
    LS_RPC_R        TYPE ZST0_BM_RPC_R.

  IF I_RPC_F-ITMTY <> GC_ITEMTYPE_TABLE
  AND I_RPC_F-ITMTY <> GC_ITEMTYPE_TEXT
  AND I_RPC_F-ITMTY <> GC_ITEMTYPE_FSV.
    MESSAGE S028(ZMS_COL_LIB) DISPLAY LIKE GC_MTYPE_E.
    RETURN.
  ENDIF.

* Init
  CALL FUNCTION 'ZFM_BM_RPC_INIT'
    EXPORTING
      I_REPID = I_RPC_F-REPID
      I_MONTH = I_RPC_F-EFMON
      I_CURMONTH = 'X'
    IMPORTING
      E_RPC_R = LS_RPC_R.

* Get SI data
  READ TABLE LS_RPC_R-FORMSTR INTO DATA(LS_RPC_F) BINARY SEARCH
    WITH KEY RPSEG = I_RPC_F-RPSEG
             RITEM = I_RPC_F-RITEM
             EFMON = I_RPC_F-EFMON.
  IF SY-SUBRC IS INITIAL.
    GS_RPC_IN_F   = LS_RPC_F.
    MOVE-CORRESPONDING I_RPC_F TO ZVI_BM_RPC_F.

    CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
      EXPORTING
        I_STRUCTURE_NAME   = 'ZST0_BM_RPC_SICELL'
        I_INTERNAL_TABNAME = 'ZST0_BM_RPC_SICELL'
      CHANGING
        CT_FIELDCAT        = GS_RPC_IN_F-FCAT.
  ENDIF.

* Get SI data
  READ TABLE LS_RPC_R-SEGMENTS INTO DATA(LS_RPC_S)
    WITH KEY RPSEG = I_RPC_F-RPSEG BINARY SEARCH.
  IF SY-SUBRC IS INITIAL.
    READ TABLE LS_RPC_S-ITEMS INTO DATA(LS_RPC_SI)
      WITH KEY RITEM = I_RPC_F-RITEM BINARY SEARCH.
    IF SY-SUBRC IS INITIAL.
      GS_RPC_IN_F-SEGITM    = LS_RPC_SI.
    ENDIF.
  ENDIF.

* Prepare output: Fieldcat, color
  PERFORM PREPARE_OUTPUT_FORM_DATA.
  GS_RPC_IN_F_O = GS_RPC_IN_F.

* Generate columns, rows
  PERFORM INIT_F_DATA CHANGING GS_RPC_IN_F.

  IF GS_RPC_IN_F-SEGITM-ITMTY = GC_ITEMTYPE_TABLE.
    ZST0_BM_RPC_DIMSET-SPRAS = 'E'.
    CALL SCREEN 0300.
  ELSE.
*    CALL SCREEN 0310.
    CALL SCREEN 0320.
  ENDIF.

ENDFUNCTION.
