*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: ZTB_BM_RPC_DIM..................................*
DATA:  BEGIN OF STATUS_ZTB_BM_RPC_DIM                .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZTB_BM_RPC_DIM                .
CONTROLS: TCTRL_ZTB_BM_RPC_DIM
            TYPE TABLEVIEW USING SCREEN '0310'.
*...processing: ZTB_BM_RPC_R....................................*
DATA:  BEGIN OF STATUS_ZTB_BM_RPC_R                  .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZTB_BM_RPC_R                  .
CONTROLS: TCTRL_ZTB_BM_RPC_R
            TYPE TABLEVIEW USING SCREEN '0110'.
*...processing: ZTB_BM_RPC_T....................................*
DATA:  BEGIN OF STATUS_ZTB_BM_RPC_T                  .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_ZTB_BM_RPC_T                  .
CONTROLS: TCTRL_ZTB_BM_RPC_T
            TYPE TABLEVIEW USING SCREEN '0300'.
*...processing: ZVI_BM_RPC_D....................................*
TABLES: ZVI_BM_RPC_D, *ZVI_BM_RPC_D. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_D
TYPE TABLEVIEW USING SCREEN '0150'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_D. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_D.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_D_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_D.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_D_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_D_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_D.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_D_TOTAL.

*...processing: ZVI_BM_RPC_F....................................*
TABLES: ZVI_BM_RPC_F, *ZVI_BM_RPC_F. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_F
TYPE TABLEVIEW USING SCREEN '0130'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_F. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_F.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_F_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_F.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_F_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_F_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_F.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_F_TOTAL.

*...processing: ZVI_BM_RPC_L....................................*
TABLES: ZVI_BM_RPC_L, *ZVI_BM_RPC_L. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_L
TYPE TABLEVIEW USING SCREEN '0140'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_L. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_L.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_L_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_L.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_L_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_L_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_L.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_L_TOTAL.

*...processing: ZVI_BM_RPC_LF...................................*
TABLES: ZVI_BM_RPC_LF, *ZVI_BM_RPC_LF. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_LF
TYPE TABLEVIEW USING SCREEN '0160'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_LF. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_LF.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_LF_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_LF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_LF_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_LF_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_LF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_LF_TOTAL.

*...processing: ZVI_BM_RPC_R....................................*
TABLES: ZVI_BM_RPC_R, *ZVI_BM_RPC_R. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_R
TYPE TABLEVIEW USING SCREEN '0112'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_R. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_R.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_R_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_R.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_R_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_R_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_R.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_R_TOTAL.

*...processing: ZVI_BM_RPC_S....................................*
TABLES: ZVI_BM_RPC_S, *ZVI_BM_RPC_S. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_S
TYPE TABLEVIEW USING SCREEN '0100'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_S. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_S.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_S_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_S.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_S_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_S_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_S.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_S_TOTAL.

*...processing: ZVI_BM_RPC_SI...................................*
TABLES: ZVI_BM_RPC_SI, *ZVI_BM_RPC_SI. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_SI
TYPE TABLEVIEW USING SCREEN '0120'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_SI. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_SI.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_SI_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SI_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_SI_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SI.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SI_TOTAL.

*...processing: ZVI_BM_RPC_SIC..................................*
TABLES: ZVI_BM_RPC_SIC, *ZVI_BM_RPC_SIC. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_SIC
TYPE TABLEVIEW USING SCREEN '0180'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_SIC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_SIC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_SIC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_SIC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIC_TOTAL.

*...processing: ZVI_BM_RPC_SICC.................................*
TABLES: ZVI_BM_RPC_SICC, *ZVI_BM_RPC_SICC. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_SICC
TYPE TABLEVIEW USING SCREEN '0190'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_SICC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_SICC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_SICC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SICC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SICC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_SICC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SICC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SICC_TOTAL.

*...processing: ZVI_BM_RPC_SIR..................................*
TABLES: ZVI_BM_RPC_SIR, *ZVI_BM_RPC_SIR. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_SIR
TYPE TABLEVIEW USING SCREEN '0170'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_SIR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_SIR.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_SIR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_SIR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIR_TOTAL.

*...processing: ZVI_BM_RPC_SIRC.................................*
TABLES: ZVI_BM_RPC_SIRC, *ZVI_BM_RPC_SIRC. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_SIRC
TYPE TABLEVIEW USING SCREEN '0200'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_SIRC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_SIRC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_SIRC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIRC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIRC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_SIRC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIRC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIRC_TOTAL.

*...processing: ZVI_BM_RPC_SIRT.................................*
TABLES: ZVI_BM_RPC_SIRT, *ZVI_BM_RPC_SIRT. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_SIRT
TYPE TABLEVIEW USING SCREEN '0210'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_SIRT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_SIRT.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_SIRT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIRT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIRT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_SIRT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_SIRT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_SIRT_TOTAL.

*...processing: ZVI_BM_RPC_W....................................*
TABLES: ZVI_BM_RPC_W, *ZVI_BM_RPC_W. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_W
TYPE TABLEVIEW USING SCREEN '0320'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_W. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_W.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_W_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_W.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_W_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_W_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_W.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_W_TOTAL.

*...processing: ZVI_BM_RPC_WC...................................*
TABLES: ZVI_BM_RPC_WC, *ZVI_BM_RPC_WC. "view work areas
CONTROLS: TCTRL_ZVI_BM_RPC_WC
TYPE TABLEVIEW USING SCREEN '0330'.
DATA: BEGIN OF STATUS_ZVI_BM_RPC_WC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_ZVI_BM_RPC_WC.
* Table for entries selected to show on screen
DATA: BEGIN OF ZVI_BM_RPC_WC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_WC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_WC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF ZVI_BM_RPC_WC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE ZVI_BM_RPC_WC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF ZVI_BM_RPC_WC_TOTAL.

*.........table declarations:.................................*
TABLES: *ZTB_BM_RPC_DIM                .
TABLES: *ZTB_BM_RPC_R                  .
TABLES: *ZTB_BM_RPC_T                  .
TABLES: ZTB_BM_RPC_D                   .
TABLES: ZTB_BM_RPC_DIM                 .
TABLES: ZTB_BM_RPC_F                   .
TABLES: ZTB_BM_RPC_L                   .
TABLES: ZTB_BM_RPC_LF                  .
TABLES: ZTB_BM_RPC_R                   .
TABLES: ZTB_BM_RPC_S                   .
TABLES: ZTB_BM_RPC_SI                  .
TABLES: ZTB_BM_RPC_SIC                 .
TABLES: ZTB_BM_RPC_SICC                .
TABLES: ZTB_BM_RPC_SIR                 .
TABLES: ZTB_BM_RPC_SIRC                .
TABLES: ZTB_BM_RPC_SIRT                .
TABLES: ZTB_BM_RPC_T                   .
TABLES: ZTB_BM_RPC_W                   .
TABLES: ZTB_BM_RPC_WC                  .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
