FUNCTION-POOL ZFG_BM_RPC.                   "MESSAGE-ID ..

* INCLUDE LZFG_BM_RPCD...                    " Local class definition
INCLUDE ZIN_COMMONTOP.
INCLUDE <CL_ALV_CONTROL>.

**********************************************************************
* CONSTANTS
**********************************************************************
CONSTANTS:
  GC_ITEMTYPE_LINE  TYPE ZDD_BM_RPC_ITMTY VALUE 'LIN',
  GC_ITEMTYPE_TABLE TYPE ZDD_BM_RPC_ITMTY VALUE 'TAB',
  GC_ITEMTYPE_TEXT  TYPE ZDD_BM_RPC_ITMTY VALUE 'TXT',
* Finacial State Version
  GC_ITEMTYPE_FSV   TYPE ZDD_BM_RPC_ITMTY VALUE 'FSV',
* Asset History Sheet
  GC_ITEMTYPE_AHS   TYPE ZDD_BM_RPC_ITMTY VALUE 'AHS',
  GC_SRCDT_FIXVAL   TYPE ZDD_BM_RPC_SRCDT VALUE '1',
  GC_SRCDT_FUNCMD   TYPE ZDD_BM_RPC_SRCDT VALUE '2',
  GC_FIGTY_KFNCP    TYPE ZDD_BM_RPC_FIGTY VALUE '1',
  GC_FIGTY_KFWCP    TYPE ZDD_BM_RPC_FIGTY VALUE '2',
  GC_FIGTY_FORMULA  TYPE ZDD_BM_RPC_FIGTY VALUE '3',
  GC_FIGTY_INPUT    TYPE ZDD_BM_RPC_FIGTY VALUE '4',
  GC_COL_OUTLENGTH  TYPE NUMC06 VALUE 20,
  GC_COLOR_HROW     TYPE CHAR4 VALUE 'C100', " 'C410',
  GC_COLOR_DESCR    TYPE CHAR4 VALUE 'C100', " 'C310',
  GC_COLOR_LDCOL    TYPE CHAR4 VALUE 'C500',
  GC_FSV_STUFE_BOLD TYPE STUFE VALUE 2,
  GC_TEMPL_FSV_4    TYPE ZDD_BM_RPC_TEMPL VALUE '042',
  GC_TEMPL_FSV_5    TYPE ZDD_BM_RPC_TEMPL VALUE '051',
  GC_MAXCOL         TYPE I VALUE 60,
  GC_HROW_2_CELLS   TYPE ZDD_BM_RPC_HROW VALUE 2,
  GC_HROW_4_CELLS   TYPE ZDD_BM_RPC_HROW VALUE 3
  .

**********************************************************************
* CLASS
**********************************************************************
CLASS LCL_EVENT_HANDLER DEFINITION .
  PUBLIC SECTION .
    METHODS:
*     Double-click control
      HANDLE_DOUBLE_CLICK
                  FOR EVENT DOUBLE_CLICK OF CL_GUI_ALV_GRID
        IMPORTING E_ROW E_COLUMN.

ENDCLASS.

**********************************************************************
* TYPES
**********************************************************************
TYPES:
  BEGIN OF GTY_SI_DB,
    SITEM   TYPE ZTB_BM_RPC_SI,
    SIROW   TYPE ZTT_BM_RPC_SIR,
    SIRT    TYPE ZTT_BM_RPC_SIRT,
    SIRCOND TYPE ZTT_BM_RPC_SIRC,
    SICOL   TYPE ZTT_BM_RPC_SIC,
    SICCOND TYPE ZTT_BM_RPC_SICC,
  END OF GTY_SI_DB,
  BEGIN OF GTY_FS_DB,
    FORMS TYPE ZTB_BM_RPC_F,
    DATA  TYPE ZTT_BM_RPC_D,
  END OF GTY_FS_DB,
  BEGIN OF GTY_ACDOCA,
    RACCT      TYPE ACDOCA-RACCT,
    GJAHR      TYPE ACDOCA-GJAHR,
    RBUKRS     TYPE ACDOCA-RBUKRS,
    POPER      TYPE ACDOCA-POPER,
    XREVERSING TYPE ACDOCA-XREVERSING,
    XREVERSED  TYPE ACDOCA-XREVERSED,
    GKONT      TYPE ACDOCA-GKONT,
    DRCRK      TYPE ACDOCA-DRCRK,
    HSL        TYPE ACDOCA-HSL,
  END OF GTY_ACDOCA,
  BEGIN OF GTY_LINE_STYLE,
    CELL1  TYPE ZDD_BM_RPC_CSTYLE,
    CELL2  TYPE ZDD_BM_RPC_CSTYLE,
    CELL3  TYPE ZDD_BM_RPC_CSTYLE,
    CELL4  TYPE ZDD_BM_RPC_CSTYLE,
    CELL5  TYPE ZDD_BM_RPC_CSTYLE,
    CELL6  TYPE ZDD_BM_RPC_CSTYLE,
    CELL7  TYPE ZDD_BM_RPC_CSTYLE,
    CELL8  TYPE ZDD_BM_RPC_CSTYLE,
    CELL9  TYPE ZDD_BM_RPC_CSTYLE,
    CELL10 TYPE ZDD_BM_RPC_CSTYLE,
    CELL11 TYPE ZDD_BM_RPC_CSTYLE,
    CELL12 TYPE ZDD_BM_RPC_CSTYLE,
    CELL13 TYPE ZDD_BM_RPC_CSTYLE,
    CELL14 TYPE ZDD_BM_RPC_CSTYLE,
    CELL15 TYPE ZDD_BM_RPC_CSTYLE,
    CELL16 TYPE ZDD_BM_RPC_CSTYLE,
    CELL17 TYPE ZDD_BM_RPC_CSTYLE,
    CELL18 TYPE ZDD_BM_RPC_CSTYLE,
    CELL19 TYPE ZDD_BM_RPC_CSTYLE,
    CELL20 TYPE ZDD_BM_RPC_CSTYLE,
    CELL21 TYPE ZDD_BM_RPC_CSTYLE,
    CELL22 TYPE ZDD_BM_RPC_CSTYLE,
    CELL23 TYPE ZDD_BM_RPC_CSTYLE,
    CELL24 TYPE ZDD_BM_RPC_CSTYLE,
    CELL25 TYPE ZDD_BM_RPC_CSTYLE,
    CELL26 TYPE ZDD_BM_RPC_CSTYLE,
    CELL27 TYPE ZDD_BM_RPC_CSTYLE,
    CELL28 TYPE ZDD_BM_RPC_CSTYLE,
    CELL29 TYPE ZDD_BM_RPC_CSTYLE,
    CELL30 TYPE ZDD_BM_RPC_CSTYLE,
    CELL31 TYPE ZDD_BM_RPC_CSTYLE,
    CELL32 TYPE ZDD_BM_RPC_CSTYLE,
    CELL33 TYPE ZDD_BM_RPC_CSTYLE,
    CELL34 TYPE ZDD_BM_RPC_CSTYLE,
    CELL35 TYPE ZDD_BM_RPC_CSTYLE,
    CELL36 TYPE ZDD_BM_RPC_CSTYLE,
    CELL37 TYPE ZDD_BM_RPC_CSTYLE,
    CELL38 TYPE ZDD_BM_RPC_CSTYLE,
    CELL39 TYPE ZDD_BM_RPC_CSTYLE,
    CELL40 TYPE ZDD_BM_RPC_CSTYLE,
    CELL41 TYPE ZDD_BM_RPC_CSTYLE,
    CELL42 TYPE ZDD_BM_RPC_CSTYLE,
    CELL43 TYPE ZDD_BM_RPC_CSTYLE,
    CELL44 TYPE ZDD_BM_RPC_CSTYLE,
    CELL45 TYPE ZDD_BM_RPC_CSTYLE,
    CELL46 TYPE ZDD_BM_RPC_CSTYLE,
    CELL47 TYPE ZDD_BM_RPC_CSTYLE,
    CELL48 TYPE ZDD_BM_RPC_CSTYLE,
    CELL49 TYPE ZDD_BM_RPC_CSTYLE,
    CELL50 TYPE ZDD_BM_RPC_CSTYLE,
    CELL51 TYPE ZDD_BM_RPC_CSTYLE,
    CELL52 TYPE ZDD_BM_RPC_CSTYLE,
    CELL53 TYPE ZDD_BM_RPC_CSTYLE,
    CELL54 TYPE ZDD_BM_RPC_CSTYLE,
  END OF GTY_LINE_STYLE.

**********************************************************************
* DATA
**********************************************************************
TABLES:
  ZVI_BM_RPC_SI, ZST0_BM_RPC_DIMSET, ZVI_BM_RPC_F.

DATA:
  GT_SRCTAB        TYPE TABLE OF TABNAMES,
  GT_RPC_T         TYPE TABLE OF ZTB_BM_RPC_T,
  GT_RPC_CHAR      TYPE TABLE OF ZST_BM_RPC_DIMFIELD,
  GT_RPC_FCHAR     TYPE TABLE OF ZST_BM_RPC_DIMFIELD,
  GT_RPC_KEYF      TYPE TABLE OF ZST_BM_RPC_DIMFIELD,
  GT_FACTOR        TYPE TT_FIELDNAME,
  GW_ERR_FACTOR    TYPE FIELDNAME,
  GW_BUKRS         TYPE BUKRS,
  GW_REPORTID      TYPE ZDD_BM_RPC_REPID,
  GS_STRUC         TYPE REF TO DATA,
  GS_LSTYLE        TYPE GTY_LINE_STYLE,
  GT_RPC_VARIABLE  TYPE TT_FIELDNAME,
  GS_RPC_R         TYPE ZST0_BM_RPC_R,
  GS_FIGTY_SCR     TYPE SY-DYNNR,
  GS_RPC_IN_F      TYPE ZST0_BM_RPC_F,
  GS_RPC_IN_F_O    TYPE ZST0_BM_RPC_F,
  GS_RPC_DS_SI     TYPE ZST0_BM_RPC_SI,
  GS_RPC_DS_SI_O   TYPE ZST0_BM_RPC_SI,
  GW_NO_SHOW_ERR   TYPE XMARK,
  GT_CONDITION     TYPE TABLE OF ZST0_BM_RPC_SELOPT,
  GO_F_ALV         TYPE REF TO CL_GUI_ALV_GRID,
  GO_F_CON         TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GO_TEXT_CON      TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GO_F_TEXT        TYPE REF TO CL_GUI_TEXTEDIT,
  GO_SI_CON        TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GO_SI_ALV        TYPE REF TO ZCL_GUI_ALV_GRID_MERGE, "CL_GUI_ALV_GRID,
  GO_SI_COND       TYPE REF TO CL_GUI_ALV_GRID,
  GO_SI_CHAR       TYPE REF TO CL_GUI_ALV_GRID,
  GO_SI_FACTOR     TYPE REF TO CL_GUI_ALV_GRID,
  GO_EVENT_HANDLER TYPE REF TO LCL_EVENT_HANDLER.

DATA:
  GT_ACDOCA     TYPE TABLE OF GTY_ACDOCA,
  GT_FAGL_011ZC TYPE TABLE OF FAGL_011ZC,
  GT_FAGL_011PC TYPE TABLE OF FAGL_011PC,
  GT_FAGL_011SC TYPE TABLE OF FAGL_011SC,
  GT_FAGLFLEXT  TYPE TABLE OF FAGLFLEXT,
  GT_BM_RPC_W   TYPE TABLE OF ZTB_BM_RPC_W,
  GT_BM_RPC_WC  TYPE TABLE OF ZTB_BM_RPC_WC.

FIELD-SYMBOLS:
  <GF_RP_WORDING> TYPE ANY.

CONSTANTS:
  GC_MARK       TYPE MARK VALUE 'X'.
