FUNCTION ZFM_BM_RPC_EXECUTE_CELL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_SIR) TYPE  ZST0_BM_RPC_SIR
*"     REFERENCE(I_SIC) TYPE  ZST0_BM_RPC_SIC
*"     REFERENCE(I_RPC_F) TYPE  ZST0_BM_RPC_F
*"  EXPORTING
*"     REFERENCE(E_CELLDATA)
*"----------------------------------------------------------------------
  DATA:
    LS_DIMENSION  TYPE ZST0_BM_RPC_DIMSET.

  CLEAR: LS_DIMENSION.

* Get dimension info from column. Column is more priority than row
  MOVE-CORRESPONDING I_SIC TO LS_DIMENSION.
  LS_DIMENSION-ROWNO = I_SIR-ROWNO.
  IF LS_DIMENSION-KEYFIG IS INITIAL.
    LS_DIMENSION-KEYFIG = I_SIR-KEYFIG.
  ENDIF.
  IF LS_DIMENSION-FORMULA IS INITIAL.
    LS_DIMENSION-FORMULA = I_SIR-FORMULA.
  ENDIF.
  IF LS_DIMENSION-SRCTAB IS INITIAL.
    LS_DIMENSION-SRCTAB = I_SIR-SRCTAB.
  ENDIF.
  IF LS_DIMENSION-AGGFUNC IS INITIAL.
    LS_DIMENSION-AGGFUNC = I_SIR-AGGFUNC.
  ENDIF.

  IF I_SIC-REVERSE IS INITIAL AND I_SIR-REVERSE IS INITIAL
  OR I_SIC-REVERSE IS NOT INITIAL AND I_SIR-REVERSE IS NOT INITIAL.
    CLEAR LS_DIMENSION-REVERSE.
  ELSE.
    LS_DIMENSION-REVERSE = 'X'.
  ENDIF.

  CASE I_SIR-FIGTY.
    WHEN GC_FIGTY_INPUT.
      CASE I_SIC-FIGTY.
        WHEN GC_FIGTY_KFWCP.
          PERFORM CELL_KEYFIGURE_GET_DATA
            USING I_RPC_F LS_DIMENSION
            CHANGING E_CELLDATA.
        WHEN GC_FIGTY_FORMULA.
          PERFORM CELL_FORMULA_CALCULATE
            USING LS_DIMENSION I_RPC_F-DATA
            CHANGING E_CELLDATA.
      ENDCASE.
    WHEN GC_FIGTY_KFNCP.
      CASE I_SIC-FIGTY.
        WHEN GC_FIGTY_KFNCP OR GC_FIGTY_KFWCP.
          PERFORM CELL_KEYFIGURE_GET_DATA
            USING I_RPC_F LS_DIMENSION
            CHANGING E_CELLDATA.
        WHEN GC_FIGTY_FORMULA.
          PERFORM CELL_FORMULA_CALCULATE
            USING LS_DIMENSION I_RPC_F-DATA
            CHANGING E_CELLDATA.
      ENDCASE.
    WHEN GC_FIGTY_KFWCP.
      CASE I_SIC-FIGTY.
        WHEN GC_FIGTY_KFNCP OR GC_FIGTY_KFWCP OR GC_FIGTY_INPUT.
          PERFORM CELL_KEYFIGURE_GET_DATA
            USING I_RPC_F LS_DIMENSION
            CHANGING E_CELLDATA.
        WHEN GC_FIGTY_FORMULA.
          PERFORM CELL_FORMULA_CALCULATE
            USING LS_DIMENSION I_RPC_F-DATA
            CHANGING E_CELLDATA.
      ENDCASE.
    WHEN GC_FIGTY_FORMULA.
      PERFORM CELL_FORMULA_CALCULATE
        USING LS_DIMENSION I_RPC_F-DATA
        CHANGING E_CELLDATA.
  ENDCASE.
ENDFUNCTION.
